// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_JRkfxjphcIxUyk1YN5zQ5EUKzNfg5E',
    appId: '1:117481681716:web:85e3b9b28fd139b1fbab61',
    messagingSenderId: '117481681716',
    projectId: 'driver-map-planner-dev',
    authDomain: 'driver-map-planner-dev.firebaseapp.com',
    storageBucket: 'driver-map-planner-dev.appspot.com',
    measurementId: 'G-CLFPPK7KD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5Uk4f9UDhF0ri9qQjNb5-F_-H7iGxn1k',
    appId: '1:117481681716:android:d07d69e794a4f191fbab61',
    messagingSenderId: '117481681716',
    projectId: 'driver-map-planner-dev',
    storageBucket: 'driver-map-planner-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAInK-jUPlZVyZeyzZQhghTrcBPdtSCvyk',
    appId: '1:117481681716:ios:801a8063962d3142fbab61',
    messagingSenderId: '117481681716',
    projectId: 'driver-map-planner-dev',
    storageBucket: 'driver-map-planner-dev.appspot.com',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAInK-jUPlZVyZeyzZQhghTrcBPdtSCvyk',
    appId: '1:117481681716:ios:881b9e8a6250f57efbab61',
    messagingSenderId: '117481681716',
    projectId: 'driver-map-planner-dev',
    storageBucket: 'driver-map-planner-dev.appspot.com',
    iosBundleId: 'com.example.driverApp.RunnerTests',
  );
}
